# Generated by Django 4.1 on 2022-08-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gloryiasapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookfreeclass',
        ),
    ]
